import { execFile } from 'node:child_process';
import { join } from 'node:path';
import { DevSwitcherError } from '../../core/errors';

/**
 * VsBridge — the MSBuild boundary layer for the Visual Studio adapter (MS-022, ADR-021).
 *
 * Mirrors the other bridges (interface_contract §6): pure parsing/formatting helpers plus
 * a process-I/O class. Stays `vscode`-free (plain paths, DevSwitcherError from `core/errors`)
 * and exec-injected so it unit-tests in plain Node without a real Visual Studio — whose
 * absence is itself the Doctor's critical-missing case (F19/E1, and the whole non-Windows
 * story: the adapter is effectively Windows-only).
 *
 * Scope (ADR-021): `.vcxproj` (C++) only — a solution's `.csproj` entries stay owned by the
 * dotnet adapter. `.sln`/`.slnx` files act as hierarchy roots (ADR-019's parent/child model).
 * Solutions and projects generated by CMake's VS generator are excluded by the CMakeCache.txt
 * marker (filterGeneratedManifests) so the CMake adapter keeps owning its build trees.
 *
 * Parsing is regex-based extraction (no XML library — ADR-009, Node built-ins only): the
 * shapes read here (.sln Project lines, .slnx Path attributes, vcxproj ProjectConfigurations)
 * are machine-written and stable enough for that; oddly-shaped files degrade to defaults.
 */

// ─────────────────────────────────────────────────────────────────────────────
// Pure helpers — paths and names
// ─────────────────────────────────────────────────────────────────────────────

/** Display name for a manifest: the filename without its extension. */
export function manifestStem(relOrPath: string): string {
  const base = relOrPath.replace(/\\/g, '/').split('/').pop() ?? relOrPath;
  return base.replace(/\.(sln|slnx|vcxproj)$/i, '');
}

/** Normalize a '/'- or '\'-separated relative path: forward slashes, `.`/`..` resolved. */
export function normalizeRelPath(path: string): string {
  const parts = path.replace(/\\/g, '/').split('/');
  const out: string[] = [];
  for (const part of parts) {
    if (part === '' || part === '.') {
      continue;
    }
    if (part === '..') {
      out.pop();
      continue;
    }
    out.push(part);
  }
  return out.join('/');
}

/** Resolve a solution-relative project reference to a workspace-relative path. */
export function resolveSlnRef(slnRel: string, refPath: string): string {
  const idx = slnRel.replace(/\\/g, '/').lastIndexOf('/');
  const dir = idx === -1 ? '' : slnRel.slice(0, idx);
  return normalizeRelPath(dir === '' ? refPath : `${dir}/${refPath}`);
}

// ─────────────────────────────────────────────────────────────────────────────
// Generated-manifest exclusion (ADR-021) — CMake's VS generator writes .sln/.slnx
// and .vcxproj files into its build tree, always next to (or under) a CMakeCache.txt.
// Excluding every manifest at or below a marker dir keeps the CMake adapter the sole
// owner of those trees and stops the switcher flooding with ZERO_CHECK/ALL_BUILD.
// ─────────────────────────────────────────────────────────────────────────────

/** The directory part of a '/'-separated rel path ('' for a workspace-root file). */
function relDir(rel: string): string {
  const idx = rel.lastIndexOf('/');
  return idx === -1 ? '' : rel.slice(0, idx);
}

/**
 * Drop manifests that live in (or under) any marker directory. `markerDirs` are the
 * workspace-relative dirs holding a CMakeCache.txt ('' = the workspace root itself,
 * which would exclude everything — that only happens when the root IS a build tree).
 */
export function filterGeneratedManifests(rels: string[], markerDirs: string[]): string[] {
  return rels.filter((rel) => {
    const dir = relDir(rel);
    return !markerDirs.some((marker) => marker === '' || dir === marker || dir.startsWith(`${marker}/`));
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// .sln / .slnx parsing — project references + solution configurations
// ─────────────────────────────────────────────────────────────────────────────

/** Project paths referenced by a classic `.sln` (as written — solution-relative,
 *  backslash-separated). All project types; the caller filters to .vcxproj (A안). */
export function parseSlnProjects(slnContent: string): string[] {
  const paths: string[] = [];
  const re = /^Project\("\{[^}]*\}"\)\s*=\s*"[^"]*"\s*,\s*"([^"]+)"/gm;
  for (let m = re.exec(slnContent); m; m = re.exec(slnContent)) {
    paths.push(m[1]);
  }
  return paths;
}

/** Project paths referenced by an XML `.slnx` (`<Project Path="…"/>`, solution-relative). */
export function parseSlnxProjects(slnxContent: string): string[] {
  const paths: string[] = [];
  const re = /<Project\b[^>]*\bPath\s*=\s*"([^"]+)"/gi;
  for (let m = re.exec(slnxContent); m; m = re.exec(slnxContent)) {
    paths.push(m[1]);
  }
  return paths;
}

/** Configurations + platforms of a solution. `.sln`: the SolutionConfigurationPlatforms
 *  section (`Debug|x64 = …`); `.slnx`: `<BuildType Name>` / `<Platform Name>` elements. */
export function parseSolutionConfigurations(
  content: string,
  kind: 'sln' | 'slnx',
): { configurations: string[]; platforms: string[] } {
  const configurations: string[] = [];
  const platforms: string[] = [];
  const push = (list: string[], value: string): void => {
    if (value && !list.includes(value)) {
      list.push(value);
    }
  };
  if (kind === 'sln') {
    const section = /GlobalSection\(SolutionConfigurationPlatforms\)[^\n]*\n([\s\S]*?)EndGlobalSection/.exec(content);
    if (section) {
      const re = /^\s*([^=|\n]+)\|([^=\n]+?)\s*=/gm;
      for (let m = re.exec(section[1]); m; m = re.exec(section[1])) {
        push(configurations, m[1].trim());
        push(platforms, m[2].trim());
      }
    }
  } else {
    const btRe = /<BuildType\b[^>]*\bName\s*=\s*"([^"]+)"/gi;
    for (let m = btRe.exec(content); m; m = btRe.exec(content)) {
      push(configurations, m[1]);
    }
    const plRe = /<Platform\b[^>]*\bName\s*=\s*"([^"]+)"/gi;
    for (let m = plRe.exec(content); m; m = plRe.exec(content)) {
      push(platforms, m[1]);
    }
  }
  return { configurations, platforms };
}

// ─────────────────────────────────────────────────────────────────────────────
// .vcxproj parsing — ProjectConfigurations + ConfigurationType
// ─────────────────────────────────────────────────────────────────────────────

/** Configurations + platforms from a vcxproj's ProjectConfigurations item group
 *  (`<ProjectConfiguration Include="Debug|x64">`). Order preserved, deduped. */
export function parseVcxprojConfigurations(content: string): { configurations: string[]; platforms: string[] } {
  const configurations: string[] = [];
  const platforms: string[] = [];
  const re = /<ProjectConfiguration\b[^>]*\bInclude\s*=\s*"([^"|]+)\|([^"]+)"/gi;
  for (let m = re.exec(content); m; m = re.exec(content)) {
    if (!configurations.includes(m[1])) {
      configurations.push(m[1]);
    }
    if (!platforms.includes(m[2])) {
      platforms.push(m[2]);
    }
  }
  return { configurations, platforms };
}

/**
 * Whether a vcxproj only produces libraries: every declared `<ConfigurationType>` is a
 * non-Application kind (StaticLibrary / DynamicLibrary / …). No ConfigurationType at all
 * reads as runnable (fail-open — the run path surfaces its own error if it is not).
 */
export function isLibraryVcxproj(content: string): boolean {
  const types: string[] = [];
  const re = /<ConfigurationType>([^<]+)<\/ConfigurationType>/gi;
  for (let m = re.exec(content); m; m = re.exec(content)) {
    types.push(m[1].trim());
  }
  return types.length > 0 && types.every((t) => t.toLowerCase() !== 'application');
}

/** Human label for a library vcxproj — validateAction / chip annotations. */
export function describeVcxprojType(content: string): string | undefined {
  const m = /<ConfigurationType>([^<]+)<\/ConfigurationType>/i.exec(content);
  if (!m) {
    return undefined;
  }
  const type = m[1].trim();
  if (type.toLowerCase() === 'application') {
    return undefined;
  }
  // StaticLibrary → 'static library', DynamicLibrary → 'dynamic library'
  return type.replace(/([a-z])([A-Z])/g, '$1 $2').toLowerCase();
}

// ─────────────────────────────────────────────────────────────────────────────
// Workspace classification (ADR-021, reusing ADR-019's parent/child model):
// a solution with ≥1 detected .vcxproj = a root ("solution"); those projects are
// its subs; a .vcxproj referenced by no solution stands alone as its own root.
// ─────────────────────────────────────────────────────────────────────────────

/** One detected VS manifest handed to classifyVsManifests. */
export interface VsManifestEntry {
  rel: string; // workspace-relative, '/'-separated
  kind: 'sln' | 'slnx' | 'vcxproj';
  content: string;
}

/** classifyVsManifests result: the manifest's role in the workspace project tree. */
export interface VsManifestRole {
  rel: string;
  kind: 'sln' | 'slnx' | 'vcxproj';
  role: 'root' | 'sub';
  /** For a sub vcxproj: the rel path of the solution that references it. */
  parentRel?: string;
  /** True when a vcxproj only produces libraries (build-only, ADR-019). */
  library: boolean;
}

/**
 * Classify detected VS manifests into solution roots and their member projects.
 * `.csproj` (and every non-vcxproj) reference is ignored — the dotnet adapter owns
 * those (A안). A solution whose references match no detected vcxproj (e.g. a C#-only
 * solution) is dropped entirely. A vcxproj referenced by several solutions belongs
 * to the first in rel order (deterministic).
 */
export function classifyVsManifests(entries: VsManifestEntry[]): VsManifestRole[] {
  const vcxByRel = new Map<string, VsManifestEntry>();
  for (const entry of entries) {
    if (entry.kind === 'vcxproj') {
      vcxByRel.set(entry.rel, entry);
    }
  }
  const solutions = entries
    .filter((e) => e.kind === 'sln' || e.kind === 'slnx')
    .sort((a, b) => a.rel.localeCompare(b.rel));

  const roles: VsManifestRole[] = [];
  const parentOf = new Map<string, string>(); // vcxproj rel → owning solution rel
  for (const sln of solutions) {
    const refs = sln.kind === 'sln' ? parseSlnProjects(sln.content) : parseSlnxProjects(sln.content);
    const members = refs
      .filter((ref) => /\.vcxproj$/i.test(ref))
      .map((ref) => resolveSlnRef(sln.rel, ref))
      .filter((rel) => vcxByRel.has(rel) && !parentOf.has(rel));
    if (members.length === 0) {
      continue; // no detected C++ members — not a switcher entry (C#-only solutions etc.)
    }
    roles.push({ rel: sln.rel, kind: sln.kind, role: 'root', library: false });
    for (const member of members) {
      parentOf.set(member, sln.rel);
    }
  }
  for (const [rel, entry] of vcxByRel) {
    const parentRel = parentOf.get(rel);
    roles.push({
      rel,
      kind: 'vcxproj',
      role: parentRel === undefined ? 'root' : 'sub',
      parentRel,
      library: isLibraryVcxproj(entry.content),
    });
  }
  return roles;
}

// ─────────────────────────────────────────────────────────────────────────────
// MSBuild argument assembly — pure (NFR-002: array args, no shell)
// ─────────────────────────────────────────────────────────────────────────────

/** `$(SolutionDir)` value for a member project — MSBuild convention requires the
 *  trailing separator. Building/evaluating a member vcxproj with its solution's dir
 *  keeps OutDir identical to a solution build (`$(SolutionDir)$(Platform)\$(Config)\`);
 *  without it a standalone build would emit into the project-local `x64\Debug\`. */
export function solutionDirProperty(solutionDir: string): string {
  const suffixed = /[\\/]$/.test(solutionDir) ? solutionDir : `${solutionDir}\\`;
  return `/p:SolutionDir=${suffixed}`;
}

/** Build args: `MSBuild <sln|vcxproj> /p:Configuration=… /p:Platform=… /m /nologo`.
 *  `solutionDir` is set for member vcxprojs so output lands where a solution build puts it. */
export function msbuildBuildArgs(
  manifestPath: string,
  configuration: string,
  platform: string,
  solutionDir?: string,
): string[] {
  const args = [manifestPath, `/p:Configuration=${configuration}`, `/p:Platform=${platform}`];
  if (solutionDir) {
    args.push(solutionDirProperty(solutionDir));
  }
  args.push('/m', '/nologo');
  return args;
}

/** Evaluation-only args for the built binary's absolute path (MSBuild 17.8+):
 *  `MSBuild <vcxproj> -getProperty:TargetPath -p:…` — no build is run. The same
 *  `solutionDir` as the build args so the evaluated path matches the build output. */
export function targetPathArgs(
  vcxprojPath: string,
  configuration: string,
  platform: string,
  solutionDir?: string,
): string[] {
  const args = [vcxprojPath, '-getProperty:TargetPath', `-p:Configuration=${configuration}`, `-p:Platform=${platform}`];
  if (solutionDir) {
    args.push(solutionDirProperty(solutionDir).replace(/^\/p:/, '-p:'));
  }
  return args;
}

/** The evaluated property value from a `-getProperty` invocation (single property →
 *  MSBuild prints the raw value). undefined when empty (property not defined). */
export function parseTargetPathOutput(stdout: string): string | undefined {
  const value = stdout.trim();
  return value === '' ? undefined : value;
}

/** The version from `msbuild -version -nologo` output — the last non-empty line. */
export function parseMsbuildVersion(stdout: string): string | undefined {
  const lines = stdout.split(/\r?\n/).map((l) => l.trim()).filter((l) => l.length > 0);
  return lines.length > 0 ? lines[lines.length - 1] : undefined;
}

// ─────────────────────────────────────────────────────────────────────────────
// MSBuild I/O boundary — exec-injected, vscode-free (mirrors the other bridges)
// ─────────────────────────────────────────────────────────────────────────────

const MAX_OUTPUT_BYTES = 8 * 1024 * 1024;

/** Captured result of one CLI invocation. */
export interface ExecResult {
  stdout: string;
  stderr: string;
  exitCode: number;
}

/** Injectable process-exec primitive (rejects only on spawn failure). */
export type VsExec = (
  command: string,
  args: string[],
  options: { cwd?: string },
) => Promise<ExecResult>;

/** Default VsExec: `child_process.execFile` with no shell (NFR-002, array args). */
export const defaultExec: VsExec = (command, args, options) =>
  new Promise((resolve, reject) => {
    execFile(
      command,
      args,
      { cwd: options.cwd, encoding: 'utf8', maxBuffer: MAX_OUTPUT_BYTES, windowsHide: true },
      (error, stdout, stderr) => {
        const code: unknown = error ? (error as { code?: unknown }).code : 0;
        if (error && typeof code !== 'number') {
          reject(new DevSwitcherError('VS_EXEC_FAILED', `Failed to run "${command}".`, error));
          return;
        }
        resolve({ stdout, stderr, exitCode: typeof code === 'number' ? code : 0 });
      },
    );
  });

/** vswhere's fixed install location (documented stable path, VS 15.2+). */
export function defaultVswherePath(): string {
  const programFilesX86 = process.env['ProgramFiles(x86)'] ?? 'C:\\Program Files (x86)';
  return join(programFilesX86, 'Microsoft Visual Studio', 'Installer', 'vswhere.exe');
}

/** Result of checkToolchain — MSBuild path + version when present (E1). */
export interface VsToolchainStatus {
  msbuild?: string; // absolute MSBuild.exe path, or 'msbuild' when only PATH resolution worked
  version?: string;
  ok: boolean;
}

/**
 * Stateful MSBuild boundary: locates MSBuild via vswhere (Build Tools included), with a
 * PATH fallback for developer prompts, and evaluates per-project TargetPath — both cached.
 * The adapter holds one instance; a missing MSBuild is the Doctor's critical case (the
 * non-Windows story: vswhere/msbuild never resolve there → Doctor ❌).
 */
export class VsBridge {
  private readonly exec: VsExec;
  private readonly vswherePath: string;
  private msbuild: VsToolchainStatus | undefined; // undefined = unprobed
  private readonly targetPathCache = new Map<string, string | undefined>();

  constructor(exec: VsExec = defaultExec, vswherePath: string = defaultVswherePath()) {
    this.exec = exec;
    this.vswherePath = vswherePath;
  }

  /** Locate MSBuild (cached). Never throws — absence yields ok:false. */
  async checkToolchain(): Promise<VsToolchainStatus> {
    if (this.msbuild === undefined) {
      this.msbuild = await this.probeMsbuild();
    }
    return this.msbuild;
  }

  /** Sync peek of the located MSBuild — for the synchronous build-task assembly
   *  (prepareInvocation probes first). 'msbuild' PATH fallback when unprobed. */
  peekMsbuild(): string {
    return this.msbuild?.msbuild ?? 'msbuild';
  }

  /**
   * Evaluate a project's built-binary path (`-getProperty:TargetPath`, evaluation only —
   * no build). Cached per (project × configuration × platform); prepareInvocation warms
   * this so the synchronous run-task assembly can peek. undefined when the property is
   * empty (library projects). Requires MSBuild 17.8+ — older MSBuild fails the eval and
   * surfaces a guidance error (the build itself still works there).
   */
  async evalTargetPath(
    vcxprojPath: string,
    configuration: string,
    platform: string,
    solutionDir?: string,
  ): Promise<string | undefined> {
    const key = this.targetKey(vcxprojPath, configuration, platform, solutionDir);
    if (this.targetPathCache.has(key)) {
      return this.targetPathCache.get(key);
    }
    const status = await this.checkToolchain();
    if (!status.ok || !status.msbuild) {
      throw new DevSwitcherError(
        'MSBUILD_NOT_FOUND',
        'MSBuild was not found. Install Visual Studio (or Build Tools) with the C++ workload — see Doctor.',
      );
    }
    const result = await this.exec(status.msbuild, targetPathArgs(vcxprojPath, configuration, platform, solutionDir), {});
    if (result.exitCode !== 0) {
      throw new DevSwitcherError(
        'VS_EVAL_FAILED',
        `MSBuild could not evaluate TargetPath for ${vcxprojPath} (exit ${result.exitCode}). ` +
          'MSBuild 17.8+ (VS 2022 17.8) is required for run/debug path resolution.',
        result.stderr || result.stdout,
      );
    }
    const path = parseTargetPathOutput(result.stdout);
    this.targetPathCache.set(key, path);
    return path;
  }

  /** Sync cache peek of an evaluated TargetPath (createRunTask; prepareInvocation warmed it). */
  peekTargetPath(vcxprojPath: string, configuration: string, platform: string, solutionDir?: string): string | undefined {
    return this.targetPathCache.get(this.targetKey(vcxprojPath, configuration, platform, solutionDir));
  }

  /** Drop all cached probes/evaluations (F17 invalidation / explicit Rescan). */
  invalidateCache(): void {
    this.msbuild = undefined;
    this.targetPathCache.clear();
  }

  private targetKey(vcxprojPath: string, configuration: string, platform: string, solutionDir?: string): string {
    return `${vcxprojPath}\0${configuration}\0${platform}\0${solutionDir ?? ''}`;
  }

  /** vswhere (Build Tools included via -products *) → PATH `msbuild` fallback → absent. */
  private async probeMsbuild(): Promise<VsToolchainStatus> {
    try {
      const found = await this.exec(
        this.vswherePath,
        ['-latest', '-products', '*', '-requires', 'Microsoft.Component.MSBuild', '-find', 'MSBuild\\**\\Bin\\MSBuild.exe'],
        {},
      );
      const first = found.stdout.split(/\r?\n/).map((l) => l.trim()).find((l) => l.length > 0);
      if (found.exitCode === 0 && first) {
        return { msbuild: first, version: await this.probeVersion(first), ok: true };
      }
    } catch {
      // vswhere absent (no VS installer, or non-Windows) — try PATH below.
    }
    try {
      const result = await this.exec('msbuild', ['-version', '-nologo'], {});
      if (result.exitCode === 0) {
        return { msbuild: 'msbuild', version: parseMsbuildVersion(result.stdout), ok: true };
      }
    } catch {
      // not on PATH either
    }
    return { ok: false };
  }

  private async probeVersion(msbuildPath: string): Promise<string | undefined> {
    try {
      const result = await this.exec(msbuildPath, ['-version', '-nologo'], {});
      return result.exitCode === 0 ? parseMsbuildVersion(result.stdout) : undefined;
    } catch {
      return undefined;
    }
  }
}
